FROM ipburger/mysql-alpine.docker:release
LABEL maintainer="daviko.50@gmail.com"

ENV MYSQL_DATABASE db_products
ENV MYSQL_USER user_products
ENV MYSQL_PASSWORD user_products
ENV MYSQL_ROOT_PASSWORD admin

CMD ["/startup.sh"]
